name: Databricks DAB CI/CD

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate-and-deploy-dev:
    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
      DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
      DATABRICKS_AUTH_TYPE: oauth-m2m

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Check authentication variables
        run: |
          if [ -z "$DATABRICKS_HOST" ]; then
            echo "ERROR: DATABRICKS_HOST is missing"
            exit 1
          fi

          if [ -z "$DATABRICKS_CLIENT_ID" ]; then
            echo "ERROR: DATABRICKS_CLIENT_ID is missing"
            exit 1
          fi

          if [ -z "$DATABRICKS_CLIENT_SECRET" ]; then
            echo "ERROR: DATABRICKS_CLIENT_SECRET is missing"
            exit 1
          fi

          echo "All Databricks authentication variables are present."

      - name: Validate DAB bundle
        run: databricks bundle validate -t dev

      - name: Deploy DAB bundle to DEV
        run: databricks bundle deploy -t dev